---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.17.13
      hooks:
          - id: commitizen
            stages: [commit-msg]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-ast
            stages: [commit]
          - id: end-of-file-fixer
            stages: [commit]
          - id: mixed-line-ending
            stages: [commit]
          - id: check-toml
            stages: [commit]
          - id: trailing-whitespace
            stages: [commit]
          - id: check-docstring-first
            stages: [commit]
          - id: check-yaml
            stages: [commit]
          - id: check-json
            stages: [commit]
          - id: pretty-format-json
            args: [--autofix, --indent=4]
            stages: [commit]
          - id: check-added-large-files
            stages: [commit]
          - id: requirements-txt-fixer
            stages: [commit]
          - id: check-merge-conflict
            stages: [commit]
          - id: debug-statements
            stages: [commit]
          - id: check-executables-have-shebangs
            language: python
            files: \.py$
            stages: [commit]
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.10
      hooks:
          - id: remove-crlf
            stages: [commit]
          - id: remove-tabs
            stages: [commit]
          - id: forbid-crlf
            stages: [commit]
          - id: forbid-tabs
            stages: [commit]
    - repo: https://github.com/myint/eradicate
      rev: v2.0.0
      hooks:
          - id: eradicate
            name: eradicate
            description: Apply eradicate
            entry: eradicate
            language: python
            files: \.py$
            args: [--in-place]
            stages: [commit]
    - repo: https://github.com/timothycrosley/isort
      rev: 5.9.2
      hooks:
          - id: isort
            name: isort
            entry: isort
            require_serial: true
            language: python
            types: [python]
            stages: [commit]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.21.0
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
            stages: [commit]
    - repo: https://github.com/ikamensh/flynt/
      rev: '0.63'
      hooks:
          - id: flynt
            stages: [commit]
    - repo: https://github.com/psf/black
      rev: 21.6b0
      hooks:
          - id: black
            description: 'Black: The uncompromising Python code formatter'
            args: [--safe]
            stages: [commit]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-docstrings
                - flake8-rst
                - flake8-rst-docstrings
                - flake8-bugbear
            stages: [commit]
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args: [-rn, -sn]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.920
      hooks:
          - id: mypy
            name: mypy
            entry: mypy
            language: python
            types_or: [python, pyi]
            stages: [commit]
